# Generated by Django 2.0.8 on 2018-09-03 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('section', models.IntegerField(default=1)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 9, 3, 16, 31, 21, 346786, tzinfo=utc))),
            ],
        ),
    ]
